### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by KarepeN** [KarepeN/Diabetes_Prediction#1]
Add the below attachment as your background image. 

![picture](https://user-images.githubusercontent.com/70028952/110188169-742a2f00-7de0-11eb-8eff-b1290924ed14.png)

**Comment by sri-vi** [comment]
okay will use this picture

**Comment by shivani-ta** [comment]
yeah

**Comment by Srivasavi-vipparla** [comment]
Thanks for using the pic
